### ISSUE TITLE
Css not loded fully.

### ISSUE THREAD

**Issue by DahalPratik** [PhuyalGaurav/social-media#9]
All of the site css is not loded. and causes this glitchy screen:
![image](https://github.com/PhuyalGaurav/crasber/assets/142107364/87c4e6eb-d610-43fc-8c86-8d300873919a)

**Comment by phuyalgaurav** [comment]
Some of the css is loaded though. Any idea whats causing this?

**Comment by DahalPratik** [comment]
No clue.

**Comment by phuyalgaurav** [comment]
Let me try locally and fix this.

**Comment by phuyalgaurav** [comment]
Fixed
